sudo: required
language: bash

# exclude tags
branches:
  except:
    - /^\d+$/

services:
  - docker

cache:
  directories:
  # these directories are typically caches for our common build tools
  # travis will keep persistent cache across builds to reduce
  # the amount of redundant work these build tools to do
  - "$HOME/.ivy2"
  - "$HOME/.sbt"


env:
  global:
    # build number used by blt pipeline
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    # disables gcloud installation prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Install envtpl for easy templating.
  - sudo pip install envtpl

  # GET credentials for artifact retrieval/publishing using env vars
  - envtpl < .nexuscredential > "$HOME/.ivy2/.credentials"

  # Login to mup.cr to publish artifacts
  - docker login --username $DOCKER_USER --password $DOCKER_PASS mup.cr

  # Install gcloud and kubectl
  - rm -rf ${HOME}/google-cloud-sdk
  - curl https://sdk.cloud.google.com | bash;
  - export PATH=${HOME}/google-cloud-sdk/bin:$PATH
  - gcloud components install kubectl

  # authenticate gcp requests the gcloud cli tool makes
  - echo $GCP_SECRET > client-secret.json
  - gcloud auth activate-service-account --key-file client-secret.json
  - export GOOGLE_APPLICATION_CREDENTIALS="$TRAVIS_BUILD_DIR/client-secret.json"

script:
  # this drives the main behavior of Travis in response to actions in the associated repo, that is
  # For master merges, this is what runs: "make publish deploy-prod"
  # For commits and PRs: "make package"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then make publish deploy-prod; else make package; fi

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(make version)
  - echo "GIT_TAG=$GIT_TAG"
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
    || true
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git push -q --tags || true

# travis calls this "semi-secret", but including it here, because we can always shut this down
# and I'd rather keep integrations transparent (not impossible to find/manage/understand)
# the following sends notifications to slack channel: #pro-builds
# see: https://meetuphq.slack.com/services/B43DLJD44
notifications:
  slack: meetuphq:c3PpDfB9g2mA49xoZLEnW98l
